# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c86a7c0d8cc210c9ee1c78aad7edefa833606e67d5095e2ac7e51841f6517168a599ad997cf500ef359c8b61553c3cdba04f59959d167e8f76f3fe45fd8b5109

test:
  secret_key_base: 47af88cbd0cfeb11a6bb69e51d76313e25b9450319ab429179f480942ac46357db63288892fb43c33dbd194008dc00b36bcf6a4842c594a9cae862a2d35a8ef2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
